name: Test On Pull Request
'on':
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test IaC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Hashicorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
      - name: Configure AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECCRET_ACCESS_KEY }}" >> $GITHUB_ENV
      - name: IaC Test
        env:
          COMMAND_IAC: terraform
        run: |
          cd infra_tf
          $COMMAND_IAC init
          $COMMAND_IAC validate
          $COMMAND_IAC plan